language: node_js
sudo: false
node_js:
- 4.2
script:
- npm test
- npm run test:eslint-import-resolver-jspm
cache:
  directories:
  - custom_jspm_packages
  - jspm_packages
  - node_modules
env:
  global:
  - secure: VXQNOQsprUQa+jbKBhjkfiWU3ISiDK083f/2BGBpypBf1zJqNpBWi/KNlSoNHNpPkoSR8Az659fY0iWSG6rLTe5equQxXHx2Ea+CaXrc660gjy1Ea2OmY034WIaInBGJfT3+1cFYvjvkIk4OkCLJSYPgkJT+joBYgAzq4i9QVd5RlaUtnDbjx6Hch7Gr9eN43zLnQ9XTzmSrkgnFYRPLDKsV0sQeOGkGMnvxCha8u+7SeLaSqb7AYSvpKJgE1fuPirIimmB6htfmHw49oGmfJhz/c9S/ceq1kM6kmMlD76Xr4ISSaPbjIx1Gk+QZh5iggLBmPBY7pqGA34xzYVHEWVe5svpxR5x+G5idTeuqIpgdJ35eK4AEHYLBe6W46V5k6BPRYvVV3HB/pqabeSuxgopvIxLNuAlqhttTAbET3dVG6OzmeQ/0MkFdB6ctqZFXYsE5B4+mcMz2uQWEC1gGewwpzqxQv2AiHHGeMg17l61Mt9sy+ma4rslCbhD0QmmN1VQVjBav3a6z6nSCxsIolWKNh/x+jPxLel2yBOwPmJTxS7pag/N1+ONQ2Gf52etSPnTpLHJuEW+CmWDTKwai7FveQfjKK/YOWucu44MySmpcfIF1KX5ZLSLwTOKCaIgiuwYbx2jn83akB4aK9VIeysZz33aNvHDiw/EqAzJokqk=
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- npm config set optional false
- npm config set loglevel warn
